# Generated by Django 5.2.6 on 2025-09-25 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField(default=0)),
                ('rate_line', models.CharField(blank=True, default='0% в день', max_length=255)),
                ('age_line', models.CharField(blank=True, default='от 18 лет', max_length=255)),
                ('btn_text', models.CharField(blank=True, default='ПОЛУЧИТЬ ДЕНЬГИ', max_length=100)),
                ('btn_url', models.URLField(blank=True, null=True)),
                ('fine_print', models.CharField(blank=True, default='Решение по заявке принимается в течение нескольких минут.', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('order_index', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order_index', 'id'],
            },
        ),
    ]
