# Generated by Django 5.2.6 on 2025-09-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_showcase_card_showcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcase',
            name='template',
            field=models.CharField(default='default', help_text='Имя папки темы из cards/templates/themes/<template>/', max_length=50),
        ),
    ]
