# Generated by Django 5.2.6 on 2025-09-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_showcase_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcase',
            name='template',
            field=models.CharField(blank=True, default='', help_text='Имя папки темы из cards/templates/themes/<template>/', max_length=50),
        ),
    ]
