# Generated by Django 5.2.6 on 2025-09-30 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_alter_showcase_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcase',
            name='slug',
            field=models.SlugField(blank=True, help_text='Только латиница, цифры, дефис. Пример: zaimy-moskva', max_length=64, null=True, unique=True, verbose_name='URL-имя (после слеша)'),
        ),
    ]
