# Generated by Django 5.2.7 on 2025-10-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_alter_showcase_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcase',
            name='slug',
            field=models.SlugField(blank=True, help_text='Только латиница, цифры, дефис. Пример: zaimy-moskva', max_length=64, null=True, verbose_name='URL-имя (после слеша)'),
        ),
    ]
