# Generated by Django 5.2.7 on 2025-10-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_alter_showcase_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcase',
            name='domains',
            field=models.TextField(blank=True, default=''),
        ),
    ]
