# Generated by Django 5.2.7 on 2025-10-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_alter_showcase_domains'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcase',
            name='extra_params',
            field=models.CharField(blank=True, help_text='Дополнительные GET-параметры (например: aff_id=42&sub=abc)', max_length=255),
        ),
        migrations.AlterField(
            model_name='card',
            name='btn_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка'),
        ),
    ]
