# Generated by Django 5.2.7 on 2025-10-01 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_showcase_extra_params_alter_card_btn_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['order_index', 'id'], 'verbose_name': 'Карточка', 'verbose_name_plural': 'Карточки'},
        ),
        migrations.AlterField(
            model_name='card',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='card',
            name='age_line',
            field=models.CharField(blank=True, default='от 18 лет', max_length=255, verbose_name='Возрастное ограничение'),
        ),
        migrations.AlterField(
            model_name='card',
            name='btn_text',
            field=models.CharField(blank=True, default='ПОЛУЧИТЬ ДЕНЬГИ', max_length=100, verbose_name='Текст кнопки'),
        ),
        migrations.AlterField(
            model_name='card',
            name='btn_url',
            field=models.URLField(blank=True, help_text='Пример: partner.ru/apply или полный https://partner.ru/apply. Схема добавится автоматически.', max_length=500, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='card',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='card',
            name='fine_print',
            field=models.CharField(blank=True, default='Решение по заявке принимается в течение нескольких минут.', max_length=255, verbose_name='Примечание мелким шрифтом'),
        ),
        migrations.AlterField(
            model_name='card',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='card',
            name='order_index',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='card',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='card',
            name='rate_line',
            field=models.CharField(blank=True, default='0% в день', max_length=255, verbose_name='Ставка'),
        ),
        migrations.AlterField(
            model_name='card',
            name='showcase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.showcase', verbose_name='Витрина'),
        ),
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
    ]
