# Generated by Django 5.2.7 on 2025-10-01 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_logo_alter_card_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='cards.logo', verbose_name='Логотип'),
        ),
    ]
